base: &base
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

pg_base: &pg_base
  <<: *base
  adapter: postgresql
  username: www-data

################################
#
## PRODUCTION
#
################################

ivy: &ivy
  <<: *pg_base
  database: hacor

meca: &meca
  <<: *pg_base
  database: meca

repo_base: &repo_base
  repositories:
    ivy:
      <<: *ivy
    meca:
      <<: *meca

################################
#
## TEST
#
################################

#ivy_test: &ivy_test
#  <<: *sqlite_base
#  # path: ./db/hacor.sqlite3
#  database: ":memory:"
#
#meca_test: &meca_test
#  <<: *sqlite_base
#  # path: ./db/meca.sqlite3
#  database: ":memory:"
#
#
#repo_base_test: &repo_base_test
#  repositories:
#    ivy:
#      <<: *ivy_test
#    meca:
#      <<: *meca_test


################################
#
# "Default" databases
#
################################

development:
  <<: *pg_base
  database: emma
  <<: *repo_base  

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#test:
#  <<: *sqlite_base
#  database: ":memory:"
#  <<: *repo_base_test

production:
  <<: *pg_base
  database: emma
  <<: *repo_base
