pg_base: &pg_base
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  username: www-data
  # host: localhost
  # password:

################################
#
## PRODUCTION
#
################################

ivy: &ivy
  <<: *pg_base
  database: ct-vis
  schema_search_path: ivy

meca: &meca
  <<: *pg_base
  database: ct-vis
  schema_search_path: meca

uma: &uma
  <<: *pg_base
  database: ct-vis
  schema_search_path: uma

repo_base: &repo_base
  repositories:
    ivy:
      <<: *ivy
    meca:
      <<: *meca
    uma:
      <<: *uma

################################
#
## TEST
#
################################

ivy_test: &ivy_test
  <<: *pg_base
  database: ct-vis-test
  schema_search_path: ivy

meca_test: &meca_test
  <<: *pg_base
  database: ct-vis-test
  schema_search_path: meca

uma_test: &uma_test
  <<: *pg_base
  database: ct-vis-test
  schema_search_path: uma

repo_base_test: &repo_base_test
  repositories:
    ivy:
      <<: *ivy_test
    meca:
      <<: *meca_test
    uma:
      <<: *uma_test


################################
#
# "Default" databases
#
################################

development:
  <<: *pg_base
  database: ct-vis
  schema_search_path: public,uma,meca,ivy
  <<: *repo_base  

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *pg_base
  database: ct-vis-test
  schema_search_path: public,uma,meca,ivy
  <<: *repo_base_test

production:
  <<: *pg_base
  database: ct-vis
  schema_search_path: public,uma,meca,ivy
  <<: *repo_base
