# Test docker compose file.  Just enough to test the Dockerfile.
version: "3.3"
services:
  visualisation:
    image: ct-vis-app
    secrets:
      - db-password
      - jwt-secret
    volumes:
      - static-content:/opt/concertim/opt/ct-visualisation-app/public
      - concertim-etc:/opt/concertim/etc
    environment:
      - METRIC_DAEMON_URL=http://metrics:3000
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - JWT_SECRET_FILE=/run/secrets/jwt-secret
    # expose:
    #   - 7000
    ports:
      - 0.0.0.0:7000:7000
    depends_on:
      - db
    networks:
      concertim-net: {}

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      concertim-net: {}

volumes:
  db-data:
  static-content:
  concertim-etc:

secrets:
  db-password:
    file: docker/secrets/db-password
  jwt-secret:
    file: docker/secrets/jwt-secret

networks:
  concertim-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
