development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ct_app_dev
  password: <%= ENV["REDIS_PASSWORD"] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ct_app_production
  password: <%= ENV["REDIS_PASSWORD"] %>
